### PR TITLE
Add 0.19 manifests and remove 0.15 manifests

### PR DESCRIPTION
**Pull request by houshengbo**
## Proposed Changes

* Add the 0.19 manifests and remove the 0.15 manifests for operator 0.19 release.

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by matzew** [comment]
I think we do not need the pre job for eventing:

https://github.com/knative/eventing/issues/4505

🤷

**Comment by houshengbo** [comment]
@matzew Do we still need pre jobs for 0.18?

**Comment by matzew** [comment]
See the PRs for
https://github.com/knative/eventing/issues/4505

we remove them on master and 0.19 release branch 

/cc @lionelvillard

**Pull request closed without merging**
