### PR TITLE
WIP: Adding two more components for scaling

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #

## Proposed Changes

* add the `filter` and `ingress` to the `haSupport` deployments

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by aliok** [comment]
I don't see leader election anywhere in https://github.com/knative/eventing/blob/6136d09fb405a605c9239f3abaf2b1ec6e5cf5e2/cmd/broker/filter/main.go#L61

Are we sure HA is enabled for broker filter? Same story for broker ingress.

**Comment by aliok** [comment]
What I mean by "" is, for example, mt broker controller is calling https://github.com/knative/eventing/blob/b482c5fad781520e3e3e0078159b4d786f408749/vendor/knative.dev/pkg/injection/sharedmain/main.go#L195 via `sharedmain.Main` here: https://github.com/knative/eventing/blob/6136d09fb405a605c9239f3abaf2b1ec6e5cf5e2/cmd/mtchannel_broker/main.go#L34

**Comment by matzew** [comment]
/close
args - I thought we had something there ... ok. until than, I close

**Pull request closed without merging**
