### PR TITLE
Return an actual newest version of the directory `latest` is not available

### LINKED ISSUE #556: Usage of `spec.version: latest` is not clear
**Describe the bug**

- https://github.com/knative/operator/pull/443 introduces `spec.version: latest` support. But it is not clear how we can use it.

**Expected behavior**

- The goal is that we want to use manifest with `serving.knative.dev/release: devel` label.

**To Reproduce**

#### 1. Add nightly manifests into `cmd/operator/kodata/knative-serving/latest/`

```
$ cd <OPERATOR_SOURCE_DIRECTORY>
$ mkdir cmd/operator/kodata/knative-serving/latest/

$ wget -O cmd/operator/kodata/knative-serving/latest/crd.yaml  https://storage.googleapis.com/knative-nightly/serving/latest/serving-crds.yaml
$ wget -O cmd/operator/kodata/knative-serving/latest/core.yaml https://storage.googleapis.com/knative-nightly/serving/latest/serving-core.yaml
```

#### 2. Install operator

```
$ ko apply -f config
```

#### 3. Set version to latest

```
cat <<-EOF | kubectl apply -f -
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: ks
spec:
  version: latest
EOF
```

#### 4. Operator fails to start

```
$ kubectl logs knative-operator-7b86d56f8c-9r9mm  -p
 ....
{"severity":"INFO","timestamp":"2021-04-13T07:46:06.779626756Z","logger":"knative-operator","caller":"knativeserving/knativeserving.go:99","message":"Reconciling KnativeServing","knative.dev/pod":"knative-operator-7b86d56f8c-9r9mm","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"5e702b0c-884e-442f-a959-ab8895e20fc3","knative.dev/key":"default/ks","status":{"observedGeneration":2,"conditions":[{"type":"DependenciesInstalled","status":"Unknown","lastTransitionTime":"2021-04-13T04:25:16Z"},{"type":"DeploymentsAvailable","status":"Unknown","lastTransitionTime":"2021-04-13T04:25:16Z"},{"type":"InstallSucceeded","status":"False","lastTransitionTime":"2021-04-13T04:27:10Z","reason":"Error","message":"Install failed with message: The manifests of the target version latest are not available to this release."},{"type":"Ready","status":"False","lastTransitionTime":"2021-04-13T04:27:10Z","reason":"Error","message":"Install failed with message: The manifests of the target version latest are not available to this release."},{"type":"VersionMigrationEligible","status":"True","lastTransitionTime":"2021-04-13T04:25:16Z"}]}}
panic: runtime error: slice bounds out of range [1:0]
```

```
$ kubectl describe knativeserving 
  ...
    Last Transition Time:  2021-04-13T04:27:10Z
    Message:               Install failed with message: The manifests of the target version latest are not available to this release.
```

**Knative release version**

HEAD (a2913e36d54c85096fcaf0045af457d56442e7a9)

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #556

## Proposed Changes

* The field spec.version is able to set to latest. If the directory `latest` is not available, return the newest actual version instead.

### CODE REVIEW

**Review by nak3 — COMMENTED** [review]
It seems that upgrade test still panicking.
Is it possible to fix the upgrade test by using this change?
Please refer to [k8s.log.txt](https://console.cloud.google.com/storage/browser/_details/knative-prow/pr-logs/pull/knative_operator/576/pull-knative-operator-serving-upgrade-tests/1391757177852530688/artifacts/466b94c1-b199-11eb-b802-a2df9403ff4e/k8s.log.txt)

```
default/knative-operator-578d98d87b-7tm8x[knative-operator]: panic: runtime error: slice bounds out of range [1:0]
...
default/knative-operator-578d98d87b-7tm8x[knative-operator]:    knative.dev/operator/pkg/reconciler/knativeserving/ingress/ingress.go:95 +0x419
...
default/knative-operator-578d98d87b-7tm8x[knative-operator]:    knative.dev/operator/pkg/reconciler/knativeserving/ingress/ingress.go:107 +0x57
default/knative-operator-578d98d87b-7tm8x[knative-operator]: knative.dev/operator/pkg/reconciler/common.Stages.Execute(0xc0004a18a8, 0x9, 0x9, 0x201e860, 0xc0009804e0, 0xc001860100, 0x204aa80, 0xc00153b400, 0x0, 0x0)
default/knative-operator-578d98d87b-7tm8x[knative-operator]:    knative.dev/operator/pkg/reconciler/common/stages.go:37 +0x83
default/knative-operator-578d98d87b-7tm8x[knative-operator]: knative.dev/operator/pkg/reconciler/knativeserving.(*Reconciler).ReconcileKind(0xc0000f8000, 0x201e860, 0xc0009804e0, 0xc00153b400, 0x0, 0x0)
```

**Comment by houshengbo** [comment]
@nak3 I should have added a test on `getIngress`.
Weird, how could the test show green mark?

**Comment by nak3** [comment]
> Weird, how could the test show green mark?

I guess that something should be fixed in the upgrade test asides from this fix.

**Comment by nak3** [comment]
Thank you @houshengbo Could you please tell me how to use the `spec.version` locally? It is different from the step with https://github.com/knative/operator/issues/556#issue-856683701 ?

**Comment by houshengbo** [comment]
@nak3 Should be no difference.
You can specify `latest` to spec.version, or any other version, like 0.22, 0.22.0, etc.
If the semantic version is not available, operator will log the error in the CR.

**Comment by nak3** [comment]
Hmm... In that case, I think this fix still does not work. I tested it but the release label is `v0.22.0`

```
$ kubectl get deploy --show-labels 
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE   LABELS
activator                          1/1     1            1           12h   serving.knative.dev/release=v0.22.0
autoscaler                         1/1     1            1           12h   serving.knative.dev/release=v0.22.0
  ...

$ kubectl get knativeserving ks -o template="{{.spec.version}}" 
latest
```

upgrade e2e test did not catch this issue as well, so I think upgrade test should be improved.

**Comment by houshengbo** [comment]
@nak3 That is what we expected.
If latest is not available, return 0.22 instead for your case.

**Comment by houshengbo** [comment]
@nak3 Here is what I did:
I created a dir called `latest`. I copied all the manifests under 0.19.0 into this directory.
Run the command `ko apply -f config`.
Everything is launched.

Apply the CR:
```
apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: latest
```

When the CR is ready, check the labels:
```
NAME               READY   UP-TO-DATE   AVAILABLE   AGE     LABELS
activator          1/1     1            1           6m      serving.knative.dev/release=v0.19.0
autoscaler         1/1     1            1           6m      serving.knative.dev/release=v0.19.0
autoscaler-hpa     1/1     1            1           5m57s   autoscaling.knative.dev/autoscaler-provider=hpa,serving.knative.dev/release=v0.19.0
controller         1/1     1            1           5m59s   serving.knative.dev/release=v0.19.0
istio-webhook      1/1     1            1           5m54s   networking.knative.dev/ingress-provider=istio,serving.knative.dev/release=v0.19.0
networking-istio   1/1     1            1           5m55s   networking.knative.dev/ingress-provider=istio,serving.knative.dev/release=v0.19.0
webhook            1/1     1            1           5m58s   serving.knative.dev/release=v0.19.0
```

The label is 0.19.0, which means the label matches what I put in the manifests. OK!

Check the CR:

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.knative.dev/v1alpha1","kind":"KnativeServing","metadata":{"annotations":{},"name":"knative-serving","namespace":"knative-serving"},"spec":{"version":"latest"}}
  creationTimestamp: "2021-05-13T12:49:09Z"
  finalizers:
  - knativeservings.operator.knative.dev
  generation: 1
  managedFields:
  - apiVersion: operator.knative.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:version: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-05-13T12:49:09Z"
  - apiVersion: operator.knative.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"knativeservings.operator.knative.dev": {}
      f:spec:
        f:cluster-local-gateway: {}
        f:controller-custom-certs:
          .: {}
          f:name: {}
          f:type: {}
        f:knative-ingress-gateway: {}
        f:registry: {}
      f:status:
        .: {}
        f:conditions: {}
        f:manifests: {}
        f:observedGeneration: {}
        f:version: {}
    manager: operator
    operation: Update
    time: "2021-05-13T12:49:21Z"
  name: knative-serving
  namespace: knative-serving
  resourceVersion: "1489581"
  selfLink: /apis/operator.knative.dev/v1alpha1/namespaces/knative-serving/knativeservings/knative-serving
  uid: 5c424b2d-75a0-40ae-977e-59a86f43bd98
spec:
  version: latest
status:
  conditions:
  - lastTransitionTime: "2021-05-13T12:49:21Z"
    status: "True"
    type: DependenciesInstalled
  - lastTransitionTime: "2021-05-13T12:51:41Z"
    status: "True"
    type: DeploymentsAvailable
  - lastTransitionTime: "2021-05-13T12:49:21Z"
    status: "True"
    type: InstallSucceeded
  - lastTransitionTime: "2021-05-13T12:51:41Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-05-13T12:49:09Z"
    status: "True"
    type: VersionMigrationEligible
  manifests:
  - /var/run/ko/knative-serving/latest
  observedGeneration: 1
  version: latest
```

spec.version is latest and status.version is latest as well. Everything seems ok.

**Comment by houshengbo** [comment]
Then, I removed the dir `latest`. Clean the cluster.
Rebuild the image `ko apply -f config`.
Everything goes up.

Apply the CR:
```
apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: latest
```

When the CR is ready, check the labels: k get deploy -n knative-serving --show-labels
```
NAME               READY   UP-TO-DATE   AVAILABLE   AGE   LABELS
activator          1/1     1            1           41s   serving.knative.dev/release=v0.22.0
autoscaler         1/1     1            1           40s   serving.knative.dev/release=v0.22.0
autoscaler-hpa     1/1     1            1           38s   autoscaling.knative.dev/autoscaler-provider=hpa,serving.knative.dev/release=v0.22.0
controller         1/1     1            1           40s   serving.knative.dev/release=v0.22.0
istio-webhook      1/1     1            1           35s   networking.knative.dev/ingress-provider=istio,serving.knative.dev/release=v0.22.1
networking-istio   1/1     1            1           35s   networking.knative.dev/ingress-provider=istio,serving.knative.dev/release=v0.22.1
webhook            1/1     1            1           39s   serving.knative.dev/release=v0.22.0
```

The newest version is 0.22, so the labels are correct.

Check the CR:
```
apiVersion: v1
items:
- apiVersion: operator.knative.dev/v1alpha1
  kind: KnativeServing
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.knative.dev/v1alpha1","kind":"KnativeServing","metadata":{"annotations":{},"name":"knative-serving","namespace":"knative-serving"},"spec":{"version":"latest"}}
    creationTimestamp: "2021-05-13T13:03:39Z"
    finalizers:
    - knativeservings.operator.knative.dev
    generation: 1
    managedFields:
    - apiVersion: operator.knative.dev/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:version: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-05-13T13:03:39Z"
    - apiVersion: operator.knative.dev/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"knativeservings.operator.knative.dev": {}
        f:spec:
          f:cluster-local-gateway: {}
          f:controller-custom-certs:
            .: {}
            f:name: {}
            f:type: {}
          f:knative-ingress-gateway: {}
          f:registry: {}
        f:status:
          .: {}
          f:conditions: {}
          f:manifests: {}
          f:observedGeneration: {}
          f:version: {}
      manager: operator
      operation: Update
      time: "2021-05-13T13:03:51Z"
    name: knative-serving
    namespace: knative-serving
    resourceVersion: "1497356"
    selfLink: /apis/operator.knative.dev/v1alpha1/namespaces/knative-serving/knativeservings/knative-serving
    uid: a2431493-fdd3-4803-a3d8-c41c5d64dd0a
  spec:
    version: latest
  status:
    conditions:
    - lastTransitionTime: "2021-05-13T13:03:51Z"
      status: "True"
      type: DependenciesInstalled
    - lastTransitionTime: "2021-05-13T13:04:21Z"
      status: "True"
      type: DeploymentsAvailable
    - lastTransitionTime: "2021-05-13T13:03:51Z"
      status: "True"
      type: InstallSucceeded
    - lastTransitionTime: "2021-05-13T13:04:21Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2021-05-13T13:03:39Z"
      status: "True"
      type: VersionMigrationEligible
    manifests:
    - /var/run/ko/knative-serving/0.22.0
    observedGeneration: 1
    version: 0.22.0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
spec.version is latest, status.version is 0.22.0.
They seems correct.

**Comment by nak3** [comment]
Thank you. Okay, I understand the "rule". When `spec.version: latest` is used for serving, `latest` directory must be created in `cmd/operator/kodata/ingress` as well. Then it worked.

**Comment by houshengbo** [comment]
Ingresses need to be in sync with the knative serving structure all the time.
There is no validation for ingress only. The validation is for knative serving. So any version working with knative serving must match the version for ingresses.

**Review by nak3 — COMMENTED** [review]
Thank you @houshengbo 
It looks good to me overall but is it not possible to catch the current panic issue https://github.com/knative/operator/issues/556#issuecomment-828047443 in upgrade test before merging this PR?
If you could improve the upgrade test to catch it, you can prove that this PR surely fixed it and can notice similar issues by causing any future change.

**Comment by houshengbo** [comment]
@nak3 I can add some logic into this function
`func getIngress(version string, manifest *mf.Manifest) error`, to check if the version is a valid semantic version, before running `semver.MajorMinor(common.SanitizeSemver(version))[1:]`.

**Comment by nak3** [comment]
That's also good but I mean that current upgrade test prints all "Passed" even though operator keeps causing go panic. It could be a upgrade test bug. We can not fix it?

**Comment by houshengbo** [comment]
@nak3 I have no idea why prow does not catch the panic :-(
What I can do with operator is to avoid the panic in golang code as much as possible.

**Review by maximilien — APPROVED** [review]
/ok-to-test
/approve
/lgtm

**Pull request merged**
