### PR TITLE
Install the webhooks after installing the deployments and services

### PR DESCRIPTION
**Pull request by houshengbo**
## Proposed Changes

* The webhooks rely on the services. The webhooks can be triggered during the installation of the manifests, because CMs are installed as well. We need to make sure that the services webhooks rely on, are installed before the installation of the webhooks.
* It may lead to some issues during the upgrading, if the webhooks are installed before the services. There is a gap the webhook is updated, but the service is not available. During this time, a change on the CM can trigger the webhook, raising errors.
* Update the manifests and dependencies for the main branch.

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/ok-to-test
/approve
/lgtm

**Review by maximilien — APPROVED** [review]
/lgtm

**Comment by markusthoemmes** [comment]
Why are there so many manifest changes in this PR? Seems to do much more than the title implies.

**Pull request merged**
