### PR TITLE
Add the OLM 0.17

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #

## Proposed Changes

*
*
*

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by aliok** [comment]
I would first send a PR to OperatorHub and once that's merged, send a PR here @houshengbo

**Comment by matzew** [comment]
What's the status of this?

**Comment by houshengbo** [comment]
The operator hub has accepted this change: https://github.com/operator-framework/community-operators/pull/2294

**Comment by markusthoemmes** [comment]
/assign @aliok 

Can we merge this now?

**Review by maximilien — APPROVED** [review]
New here but seems fine to me as this is prep for new version (guessing)
/ok-to-test

**Pull request closed without merging**
