### PR TITLE
Drop autoscaling/v2beta1 and policy/v1beta1

### PR DESCRIPTION
**Pull request by nak3**
## Proposed Changes

* As per title, these APIs are no longer supported on current supported k8s versions.

**Release Note**

```release-note
autoscaling/v2beta1 and policy/v1beta1 are no longer supported. Please use autoscaling/v2 and policy/v1 if you are using custom manifests.
```

### CODE REVIEW

**Comment by nak3** [comment]
/retest

```
    prober.go:106: expecting to have 3522 unique events received, but received 3502 unique events
```

**Review by ReToCode — APPROVED** [review]
/lgtm

Are we good on this in the YAML manifests in other repos?

**Pull request merged**
