### PR TITLE
[release-1.7] Fix the RBAC issue for kafka eventing source

### LINKED ISSUE #1274: Operator fails to install Knative Eventing when Kafka specified
It seems that there has been some recent changes which causes Knative Operator to fail installing Knative eventing when Kafka source is specified. This worked a week ago. Strange is that it now it doesn't work neither for 1.8 nor 1.7 version.

In the pod there is following error:

```
{"severity":"ERROR","timestamp":"2022-11-01T23:56:53.738229144Z","logger":"knative-operator","caller":"controller/controller.go:566","message":"Reconcile error","commit":"0c153ec-dirty","knative.dev/pod":"knative-operator-54c47c9ccc-4xsbl","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeeventing.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeEventing","knative.dev/traceid":"df2aef9f-85fc-4c4e-bcfe-7480d4263792","knative.dev/key":"default/knative-eventing","duration":"7.220543133s","error":"failed to apply (cluster)rolebindings: clusterrolebindings.rbac.authorization.k8s.io \"kafka-controller\" is forbidden: user \"system:serviceaccount:default:knative-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:default\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"*\"], Resources:[\"configmaps\"], Verbs:[\"delete\" \"get\" \"list\" \"watch\" \"update\" \"create\" \"delete\"]}\n{APIGroups:[\"*\"], Resources:[\"events\"], Verbs:[\"patch\" \"create\"]}\n{APIGroups:[\"*\"], Resources:[\"nodes\"], Verbs:[\"get\" \"list\" \"watch\"]}\n{APIGroups:[\"*\"], Resources:[\"pods\"], Verbs:[\"list\" \"update\" \"get\" \"watch\"]}\n{APIGroups:[\"*\"], Resources:[\"pods/finalizers\"], Verbs:[\"get\" \"list\" \"create\" \"update\" \"delete\"]}\n{APIGroups:[\"*\"], Resources:[\"secrets\"], Verbs:[\"list\" \"get\" \"update\" \"watch\"]}\n{APIGroups:[\"*\"], Resources:[\"serviceaccounts\"], Verbs:[\"get\" \"list\" \"watch\" \"update\" \"create\" \"delete\"]}\n{APIGroups:[\"*\"], Resources:[\"services\"], Verbs:[\"get\" \"list\" \"watch\" \"update\" \"create\" \"delete\"]}\n{APIGroups:[\"apps\"], Resources:[\"statefulsets/scale\"], Verbs:[\"get\" \"list\" \"watch\" \"update\" \"patch\"]}\n{APIGroups:[\"internal.kafka.eventing.knative.dev\"], Resources:[\"consumergroups\"], Verbs:[\"create\" \"get\" \"list\" \"watch\" \"patch\" \"update\" \"delete\"]}\n{APIGroups:[\"internal.kafka.eventing.knative.dev\"], Resources:[\"consumergroups/finalizers\"], Verbs:[\"update\" \"delete\"]}\n{APIGroups:[\"internal.kafka.eventing.knative.dev\"], Resources:[\"consumergroups/status\"], Verbs:[\"create\" \"get\" \"list\" \"watch\" \"patch\" \"update\" \"delete\"]}\n{APIGroups:[\"internal.kafka.eventing.knative.dev\"], Resources:[\"consumers\"], Verbs:[\"create\" \"get\" \"list\" \"watch\" \"patch\" \"update\" \"delete\"]}\n{APIGroups:[\"internal.kafka.eventing.knative.dev\"], Resources:[\"consumers/finalizers\"], Verbs:[\"update\" \"delete\"]}\n{APIGroups:[\"internal.kafka.eventing.knative.dev\"], Resources:[\"consumers/status\"], Verbs:[\"create\" \"get\" \"list\" \"watch\" \"patch\" \"update\" \"delete\"]}\n{APIGroups:[\"rbac.authorization.k8s.io\"], Resources:[\"clusterrolebindings\"], Verbs:[\"watch\"]}","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220818004048-4a03844c0b15/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220818004048-4a03844c0b15/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220818004048-4a03844c0b15/controller/controller.go:491"}

```

The manifest is following:

```
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  # ...
  source:
    kafka:
      enabled: true
```

Note that if I comment out the kafka source (and thus leave default rabbitmq source to be installed) everything installs correctly.

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #1274 for 1.7

### CODE REVIEW

**Comment by matzew** [comment]
@houshengbo  any bug report?

**Review by matzew — APPROVED** [review]
/lgtm
/approve

Looks reasonable and is similar to "main", but wondering if there was an actual issue?
/hold

**Comment by houshengbo** [comment]
@matzew Added the bug link in the comment.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
