### PR TITLE
Move to Security-Guard 0.6

### PR DESCRIPTION
**Pull request by davidhadas**
Moved to Security-Guard 0.6

### CODE REVIEW

**Comment by houshengbo** [comment]
run  ./hack/update-codegen.sh, to update the manifests for security guard.

**Comment by davidhadas** [comment]
> ./hack/update-codegen.sh

hi @houshengbo, 
I already did - what may be the reason that `./hack/update-codegen.sh` does not pick up 0.6?

**Comment by davidhadas** [comment]
/unhold
0.6.1 is released

**Comment by davidhadas** [comment]
#1611 seem to resolve this.
Closing..

**Pull request closed without merging**
