### PR TITLE
Add linting config and fix issues.

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Proposed Changes

As per title, prep for CI automation checking this.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by cardil** [comment]
Such changes are cool, I'm 100% behind them, but we should first propose that on productivity WG. Then do that to all repos.

**Comment by markusthoemmes** [comment]
@cardil this was in fact the last repository to be onboarded, automation has already been rolled out.

**Pull request merged**
