### PR TITLE
Update to latest manifestival to fix an issue on CRD/v1 transformer

### LINKED ISSUE #223: CRD/v1 conversion webhook cannot correctly be transformed to the specified namespace
**Describe the bug**
When deploy eventing components in specified namespace(such as knative-system) through the operator,  the conversion.webhook of CRD such as brokers.eventing.knative.dev still points to knative-eventing.

**Expected behavior**
Deploy the eventing component in specified namespace, CRD conversion.webhook points to the specified namespace.

**Knative release version**
0.16

### PR DESCRIPTION
**Pull request by jimoosciuc**
Update to latest manifestival.
Fixes #223

### CODE REVIEW

**Comment by houshengbo** [comment]
@jimoosciuc Could you rebase this PR? The prow issue with upgrade should have been fixed.

**Comment by jimoosciuc** [comment]
Thank you for your reminder. After rebase, I found that the error still occurred. I checked the build log and related test code, but still no clues to the problem. The following is the error message:

```
==========================================================
==== RUNNING POSTDOWNGRADE TESTS FOR KNATIVE EVENTING ====
==========================================================
==== Tue Aug 11 20:46:32 PDT 2020
==========================================================
Running tests with 'go test -v  -race -count=1 -tags=postdowngrade -timeout=20m ./test/upgrade '
=== RUN   TestPostDowngrade
=== PAUSE TestPostDowngrade
=== CONT  TestPostDowngrade
=== RUN   TestPostDowngrade/InMemoryChannel-messaging.knative.dev/v1beta1
    channel_single_event_helper.go:59: Run test with channel {"InMemoryChannel" "messaging.knative.dev/v1beta1"}
    test_runner.go:99: namespace is : "test-post-downgrade-in-memory-channel-messaging-knative-depqn2g"
=== PAUSE TestPostDowngrade/InMemoryChannel-messaging.knative.dev/v1beta1
=== CONT  TestPostDowngrade/InMemoryChannel-messaging.knative.dev/v1beta1
    creation.go:55: Creating channel &TypeMeta{Kind:InMemoryChannel,APIVersion:messaging.knative.dev/v1beta1,}-e2e-singleevent-channel-binary
    creation.go:411: Creating pod &Pod{ObjectMeta:{e2e-singleevent-event-record-pod-binary  test-post-downgrade-in-memory-channel-messaging-knative-depqn2g    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[e2etest:dfb876fa-5ea5-4cdd-adb8-4228d16b5227] map[] [] []  []},Spec:PodSpec{Volumes:[]Volume{},Containers:[]Container{Container{Name:recordevents,Image:gcr.io/knative-boskos-17/koperator-e2e-img/12831/recordevents:latest,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{EnvVar{Name:K_CONFIG_TRACING,Value:{"backend":"none","debug":"false","sample-rate":"0.1"},ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,},},RestartPolicy:Always,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[]LocalObjectReference{},Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[]Container{},AutomountServiceAccountToken:nil,Tolerations:[]Toleration{},HostAliases:[]HostAlias{},PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[]PodReadinessGate{},RuntimeClassName:nil,EnableServiceLinks:nil,PreemptionPolicy:nil,Overhead:ResourceList{},TopologySpreadConstraints:[]TopologySpreadConstraint{},EphemeralContainers:[]EphemeralContainer{},},Status:PodStatus{Phase:,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{},QOSClass:,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{},EphemeralContainerStatuses:[]ContainerStatus{},},}
    operation.go:105: Waiting for 1 endpoints in service e2e-singleevent-event-record-pod-binary
    monitoring.go:78: Executing command: kubectl port-forward e2e-singleevent-event-record-pod-binary 51996:8392 -n test-post-downgrade-in-memory-channel-messaging-knative-depqn2g
    monitoring.go:71: running e2e-singleevent-event-record-pod-binary port-forward in background, pid = 59057
    creation.go:104: Creating v1beta1 subscription e2e-singleevent-subscription-binary for channel &TypeMeta{Kind:InMemoryChannel,APIVersion:messaging.knative.dev/v1beta1,}-e2e-singleevent-channel-binary
    tracker.go:152: Waiting for all KResources to become ready
    operation.go:100: Failed to get all test resources ready: failed waiting for {TypeMeta:{Kind:Subscription APIVersion:messaging.knative.dev/v1beta1} ObjectMeta:{Name:e2e-singleevent-subscription-binary GenerateName: Namespace:test-post-downgrade-in-memory-channel-messaging-knative-depqn2g SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]}} to become ready: timed out waiting for the condition
        knative.dev/eventing/test/lib.(*Client).WaitForAllTestResourcesReadyOrFail
        	/home/prow/go/src/knative.dev/eventing/test/lib/operation.go:100
        knative.dev/eventing/test/e2e/helpers.SingleEventForChannelTestHelper.func1
        	/home/prow/go/src/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go:96
        knative.dev/eventing/test/lib.(*ComponentsTestRunner).RunTests.func1
        	/home/prow/go/src/knative.dev/eventing/test/lib/test_runner.go:70
        testing.tRunner
        	/root/.gvm/gos/go1.14.6/src/testing/testing.go:1039
        runtime.goexit
        	/root/.gvm/gos/go1.14.6/src/runtime/asm_amd64.s:1373
```

Although this commit will change the address of the CRD conversion webhook, I saw that the test code is fixed to knative-eventing namespace, so there should be no impact.I debugged for a few days and I didn't find a solution.

**Comment by houshengbo** [comment]
@jimoosciuc This PR updates the dependency of manifestival, which resolved the webhook transformation issue, so namespace for knative eventing should not be the issue.
Honestly, the eventing downgrade tests are not stable. Sometimes the issues are gone when retesting.

**Comment by houshengbo** [comment]
/lgtm
/approve

Thanks!!

**Comment by houshengbo** [comment]
@jimoosciuc I also opened another PR to update manifestival package, https://github.com/knative/operator/pull/229
 the prow is able to pass. I re-triggered the upgrade prow for this PR, but have not seen it passed.

**Comment by jimoosciuc** [comment]
@houshengbo It seems that the downgrade test failed again, but I found that in the test script(test/e2e-upgrade-tests.sh), after the install_previous_operator_release function is executed, it only waits for pod up instead of waiting for the eventing component to be updated before running the test case. Could this be the cause of downgrade test unstable?

**Comment by houshengbo** [comment]
@jimoosciuc I am not 100% sure of the cause, but your catch is a valid point. 
Let me quickly add another `postdowngrade` tests in operator to verify the deployment resources, with specific version.
This can make sure the other tests can run after the downgrade is finished.

**Comment by houshengbo** [comment]
@jimoosciuc i updated the test cases. could you rebase again?

**Comment by jimoosciuc** [comment]
@houshengbo It looks like the test failed again 😂, but this time the error is different:
```
=== Failed
=== FAIL: test/downgrade TestKnativeServingPostDowngrade/verify_resources (300.88s)
    knativeresources.go:109: The deployment networking-istio is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment networking-istio is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment webhook is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment autoscaler-hpa is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment autoscaler-hpa is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment autoscaler-hpa is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment autoscaler-hpa is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    knativeresources.go:109: The deployment activator is not ready.
    verify.go:263: Knative Serving deployments failed to meet the expected deployments: timed out waiting for the condition
    --- FAIL: TestKnativeServingPostDowngrade/verify_resources (300.88s)

=== FAIL: test/downgrade TestKnativeServingPostDowngrade (301.00s)


DONE 4 tests, 2 failures in 329.166s
Finished run, return code is 1
```

**Comment by houshengbo** [comment]
@jimoosciuc The downgrade is unstable with operator. Let's give it one more try.

**Comment by houshengbo** [comment]
@jimoosciuc I encourage you to join the knative community. PLZ follow the link here: https://github.com/knative/operator/pull/224#issuecomment-668410759.

I opened another PR #237, which is exactly the same one as yours. I picked up your commits, and added you as the co-author. If we can make this PR pass, shall we use that one to merge? As you see, the prow jobs passed there.

**Comment by jimoosciuc** [comment]
@houshengbo Thanks for your suggestion, I agree with this.

**Comment by houshengbo** [comment]
@jimoosciuc Could you write `@googlebot I consent` as a comment for this PR, and #237 ?
The PR is asking for author's consensus.

**Comment by jimoosciuc** [comment]
@googlebot I consent

**Pull request merged**
