### PR TITLE
Update to latest manifestival to fix an issue on CRD/v1 transformer #224 

### LINKED ISSUE #223: CRD/v1 conversion webhook cannot correctly be transformed to the specified namespace
**Describe the bug**
When deploy eventing components in specified namespace(such as knative-system) through the operator,  the conversion.webhook of CRD such as brokers.eventing.knative.dev still points to knative-eventing.

**Expected behavior**
Deploy the eventing component in specified namespace, CRD conversion.webhook points to the specified namespace.

**Knative release version**
0.16

### PR DESCRIPTION
**Pull request by houshengbo**
Update to latest manifestival.
Fixes #223
co-authored-by: jimoosciuc <jimoosciuc@163.com>

### CODE REVIEW

**Comment by houshengbo** [comment]
@googlebot I consent.

**Comment by houshengbo** [comment]
@googlebot I consent

**Comment by houshengbo** [comment]
`@googlebot I consent`

**Comment by houshengbo** [comment]
@googlebot I consent

**Comment by houshengbo** [comment]
cla: yes

**Comment by jimoosciuc** [comment]
@googlebot I consent

**Pull request closed without merging**
