### PR TITLE
 Add 0.17 manifests into the operator

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes: #253

## Proposed Changes

* This PR added the 0.17 manifests into the operator.
* The Upgrade Prow changed the previous version of Knative into 0.16.

### CODE REVIEW

**Comment by evankanderson** [comment]
Is there a script that picks these up and redoes the naming, or is that by hand?

**Comment by houshengbo** [comment]
@evankanderson So far, this is done manually.

**Comment by houshengbo** [comment]
All resources:
CRDs first, post jobs last.

For other resources in the middle:
Key component first, other components second.

**Pull request merged**
