### PR TITLE
[RELEASE-0.14] Pin test-infra to release-0.14.

### LINKED ISSUE #127: release 0.14 branch can not run `update deps`
**Describe the bug**

running the `./hack/update-deps.sh`, I am getting:

```
Error: errors for ["_/home/matzew/go/src/knative.dev/operator/cmd/_"]:
_/home/matzew/go/src/knative.dev/operator/cmd/_: -: cannot find package "." in:
	/home/matzew/go/src/knative.dev/operator/cmd/*
Usage:
  licenses save <package> [flags]

Flags:
      --force              Delete the destination directory if it already exists.
  -h, --help               help for save
      --save_path string   Directory into which files should be saved that are required by license terms

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --confidence_threshold float       Minimum confidence required in order to positively identify a license. (default 0.9)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

F0604 13:48:11.438023 1466482 main.go:43] errors for ["_/home/matzew/go/src/knative.dev/operator/cmd/_"]:
_/home/matzew/go/src/knative.dev/operator/cmd/_: -: cannot find package "." in:
	/home/matzew/go/src/knative.dev/operator/cmd/*

```

**Expected behavior**

works, like on master

### PR DESCRIPTION
**Pull request by markusthoemmes**
Fixes #127

## Proposed Changes

We didn't pin the test infra package when cutting the 0.14 release. Pinning it fixes is the right thing and it contains a switch from go-licenses to dep-collector which I think fixes the issue above.

**Release Note**

```release-note
NONE
```

/assign @matzew

### CODE REVIEW

**Comment by matzew** [comment]
I am getting

```
./hack/update-deps.sh
2020/06/05 10:16:20 Error collecting transitive dependencies: go/build: importGo knative.dev/operator/cmd/eventing-operator: exit status 1
go: finding knative.dev/eventing/pkg/apis/config latest
go: finding knative.dev/eventing/pkg latest
go: finding knative.dev/eventing/pkg/apis latest
go: finding knative.dev/eventing/pkg/apis/eventing latest
build knative.dev/operator/cmd/eventing-operator: cannot load knative.dev/eventing/pkg/apis/config: no matching versions for query "latest"
```

**Comment by matzew** [comment]
some more data

```
➜  operator git:(8a0d017) ✗ 
➜  operator git:(8a0d017) ✗ 
➜  operator git:(8a0d017) ✗ pwd
/home/matzew/go/src/knative.dev/operator
➜  operator git:(8a0d017) ✗ go version
go version go1.13.1 linux/amd64
➜  operator git:(8a0d017) ✗ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/matzew/go/bin"
GOCACHE="/home/matzew/.cache/go-build"
GOENV="/home/matzew/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/matzew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/matzew/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build197290294=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by houshengbo** [comment]
I downloaded this PR.
Test it with both 
`./hack/update-deps.sh` and `./hack/update-deps.sh --upgrade`.
They both worked.

**Pull request merged**
