### PR TITLE
Adding istio ignore annotation transformer for jobs

### LINKED ISSUE #159: Add the job sidecar transformer to all the job
**Describe the bug**
The resources Job needs to be have the annotation `"sidecar.istio.io/inject": "false"`.

**Expected behavior**
Operator needs to have a transformer func to add this annotation.

**Knative release version**
All.

### PR DESCRIPTION
**Pull request by AceHack**
/lint

Fixes #159

**Release Note**
```release-note
Automatically adds `sidecar.istio.io/inject: false` to any jobs
```

### CODE REVIEW

**Comment by AceHack** [comment]
@houshengbo @Cynocracy These failures seem related to the recently added post downgrade tests.
https://github.com/knative/operator/pull/235

The changes I've made here add `sidecar.istio.io/inject: false` if it doesn't already exist on jobs.  Since it already exists on jobs, this results in basically a no-op today.  So I don't see how it could have affected these tests.  Thanks and let me know any suggestions you might have.

**Comment by houshengbo** [comment]
@AceHack It is true that the downgrade is not stable.
It is hard for me to hack, coz when I tried locally, it turned out fine.
However, in the prow job of upgrade, the downgrade part fails every a few builds.
Sometimes, it fails to remove some obsolete resources; sometimes, it fails to go back to the old version for the deployment resource...

**Comment by houshengbo** [comment]
@Cynocracy I am asking myself again: if upgrade is going fine, why do I care the downgrade?

**Pull request merged**
