### PR TITLE
fix: does not panic when errors occur during delete

### PR DESCRIPTION
**Pull request by l-qing**
Ref:
- https://github.com/manifestival/manifestival/issues/92

I encountered a panic in my environment.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1162cb8]

goroutine 968 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetKind(...)
	k8s.io/apimachinery@v0.22.5/pkg/apis/meta/v1/unstructured/unstructured.go:226
github.com/manifestival/manifestival.okToDelete(0x0)
	github.com/manifestival/manifestival@v0.7.1/manifestival.go:234 +0x38
github.com/manifestival/manifestival.Manifest.delete({{0xc000798000, 0x34, 0x40}, {0x1cca770, 0xc000288c30}, {{0x1ceb360, 0xc00014f470}, 0x0}}, 0x1cca770, {0x0, ...})
	github.com/manifestival/manifestival@v0.7.1/manifestival.go:179 +0xae
github.com/manifestival/manifestival.Manifest.Delete({{0xc000798000, 0x34, 0x40}, {0x1cca770, 0xc000288c30}, {{0x1ceb360, 0xc00014f470}, 0x0}}, {0x0, 0x0, ...})
	github.com/manifestival/manifestival@v0.7.1/manifestival.go:116 +0x1e5
knative.dev/operator/pkg/reconciler/common.Uninstall(0xc0006cf000)
	knative.dev/operator/pkg/reconciler/common/install.go:76 +0x278
knative.dev/operator/pkg/reconciler/knativeserving.(*Reconciler).FinalizeKind(0xc0004be620, {0x1cca658, 0xc000d4d740}, 0xc000594660)
	knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go:86 +0x365
knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving.(*reconcilerImpl).Reconcile(0xc00021e1e0, {0x1cca658, 0xc000d4d710}, {0xc001266900, 0x19})
	knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go:240 +0x518
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc000a9c660)
	knative.dev/pkg@v0.0.0-20220126214246-d7b329c36019/controller/controller.go:542 +0x5a5
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	knative.dev/pkg@v0.0.0-20220126214246-d7b329c36019/controller/controller.go:478 +0x68
created by knative.dev/pkg/controller.(*Impl).RunContext
	knative.dev/pkg@v0.0.0-20220126214246-d7b329c36019/controller/controller.go:476 +0x2de
```

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Review by houshengbo — APPROVED** [review]
/lgtm
/approve

**Comment by houshengbo** [comment]
@l-qing 
Please join the list of contributors, so that we do not need the ok-to-test label any more.
This is an example: https://github.com/knative/community/pull/1264/files
You can also add your company as adopter: https://github.com/knative/community/pull/1309

**Comment by l-qing** [comment]
Hi @houshengbo, I solved the unit test failure problem. Could you please help review it again? Thanks!

**Comment by l-qing** [comment]
> @l-qing Please join the list of contributors, so that we do not need the ok-to-test label any more. This is an example: https://github.com/knative/community/pull/1264/files You can also add your company as adopter: [knative/community#1309](https://github.com/knative/community/pull/1309)

Thank you for your suggestion and invitation. I'll consider it.

**Comment by houshengbo** [comment]
maybe just run "./hack/update-codegen.sh" to catch up the changes.

**Comment by l-qing** [comment]
> maybe just run "./hack/update-codegen.sh" to catch up the changes.

That's exactly as you said.
```
Run # From: https://backreference.org/2009/12/23/how-to-match-newlines-in-sed/
Found diffs in: vendor/k8s.io/code-generator/generate-groups.sh
vendor/knative.dev/pkg/hack/generate-knative.sh
Error: Please run ./hack/update-codegen.sh.
diff --git a/vendor/k8s.io/code-generator/generate-groups.sh b/vendor/k8s.io/code-generator/generate-groups.sh
old mode 100755
new mode 100644
Error: Please run ./hack/update-codegen.sh.
diff --git a/vendor/knative.dev/pkg/hack/generate-knative.sh b/vendor/knative.dev/pkg/hack/generate-knative.sh
old mode 100755
new mode 100644
knative/operator is out of date. Please run hack/update-codegen.sh
Error: Process completed with exit code 1.
```

I'm just curious, why does it take so many impacts to modify one line of code? 😁

**Comment by houshengbo** [comment]
The prow CI checks every pr in terms of whether it has the latest manifests and dependencies.
When there is a mismatch, you have to update your pr accordingly.

**Comment by l-qing** [comment]
Due to this issue, the CI task has currently failed and I have no choice but to wait for a longer period of time.
* https://github.com/knative/toolbox/pull/7#issuecomment-1500139701
* https://github.com/knative/toolbox/pull/9#issuecomment-1500216080

**Comment by houshengbo** [comment]
@l-qing Currently prows across many knative projects have run into the same issue. We need to fix it first, before merging this pr.

**Comment by l-qing** [comment]
Hi @houshengbo, my CI tasks passed. Could you please give it an `LGTM` label when you have time? Thanks!

**Comment by l-qing** [comment]
> /lgtm

Thanks!

**Pull request merged**
