### PR TITLE
Update go.mod to specify the module is go1.14

### PR DESCRIPTION
**Pull request by dprotaso**
Thus the go commands will default to -mod=vendor

See: https://golang.org/doc/go1.14#go-command

### CODE REVIEW

**Comment by dprotaso** [comment]
> Now using version go1.13.10 in local package set

hmm...

**Comment by dprotaso** [comment]
should be good to merge CI is using go1.14

**Comment by Cynocracy** [comment]
oh and /approved

**Comment by Cynocracy** [comment]
/lgtm /approve

OK I finally did it. Haha. You're good to go.

**Pull request merged**
