### PR TITLE
Pin knative/pkg and knative/test-infra to release-0.17

### PR DESCRIPTION
**Pull request by Harwayne**
## Proposed Changes

- Pin knative/pkg and knative/test-infra to `release-0.17`.
    - In preparation for `release-0.17` of knative/operator in a week.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by houshengbo** [comment]
@Harwayne 
Do you know how to resolve this issue?
```
2020/08/11 21:37:49 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
2020/08/11 21:37:49 Registering 2 clients
2020/08/11 21:37:49 Registering 3 informer factories
2020/08/11 21:37:49 Registering 3 informers
2020/08/11 21:37:49 Registering 2 controllers
{"level":"info","ts":"2020-08-11T21:37:49.301Z","caller":"logging/config.go:110","msg":"Successfully created the logger."}
{"level":"info","ts":"2020-08-11T21:37:49.302Z","caller":"logging/config.go:111","msg":"Logging level set to info"}
{"level":"info","ts":"2020-08-11T21:37:49.302Z","caller":"logging/config.go:78","msg":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":"2020-08-11T21:37:49.302Z","logger":"knative-operator","caller":"profiling/server.go:59","msg":"Profiling enabled: false"}
{"level":"info","ts":"2020-08-11T21:37:49.308Z","logger":"knative-operator","caller":"leaderelection/context.go:46","msg":"Running with Standard leader election"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ecc8b]

goroutine 1 [running]:
k8s.io/client-go/rest.CopyConfig(0x0, 0xc00061b200)
	k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/rest/config.go:569 +0x3b
k8s.io/client-go/dynamic.ConfigFor(0x0, 0xc00079f510)
	k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/dynamic/simple.go:41 +0x2f
k8s.io/client-go/dynamic.NewForConfig(0x0, 0x4959f8, 0xc00061b4d0, 0x18d4ca0, 0x2d5c710)
	k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/dynamic/simple.go:63 +0x2f
github.com/manifestival/client-go-client/pkg/dynamic.NewForConfig(0x0, 0x4959f8, 0xc0001b9d10, 0x18d4ca0, 0x2d5c710)
	github.com/manifestival/client-go-client@v0.2.3-0.20200702141517-e255fbf14f6f/pkg/dynamic/rest_mapper_resource_interface.go:18 +0x2f
github.com/manifestival/client-go-client.NewClient(0x0, 0x18d4ca0, 0x2d5c710, 0x0, 0x0)
	github.com/manifestival/client-go-client@v0.2.3-0.20200702141517-e255fbf14f6f/client.go:24 +0x2f
knative.dev/operator/pkg/reconciler/knativeserving.NewExtendedController.func1(0x1f42d00, 0xc00075bf80, 0x1f0bf80, 0xc000093320, 0x2d5c710)
	knative.dev/operator/pkg/reconciler/knativeserving/controller.go:52 +0x19b
knative.dev/operator/pkg/reconciler/knativeserving.NewController(0x1f42d00, 0xc00075bf80, 0x1f0bf80, 0xc000093320, 0xc0002ebc00)
	knative.dev/operator/pkg/reconciler/knativeserving/controller.go:41 +0x5e
knative.dev/pkg/injection/sharedmain.ControllersAndWebhooksFromCtors(0x1f42d00, 0xc00075bf80, 0xc000093320, 0xc00079ff68, 0x2, 0x2, 0x1, 0x37e11d600, 0x2540be400, 0x77359400, ...)
	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:396 +0x17b
knative.dev/pkg/injection/sharedmain.MainWithConfig(0x1f43880, 0xc00000e118, 0x1b4a473, 0x10, 0xc000728000, 0xc00079ff68, 0x2, 0x2)
	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:216 +0x69c
knative.dev/pkg/injection/sharedmain.MainWithContext(0x1f43880, 0xc00000e118, 0x1b4a473, 0x10, 0xc00079ff68, 0x2, 0x2)
	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:160 +0xd5
knative.dev/pkg/injection/sharedmain.Main(0x1b4a473, 0x10, 0xc00079ff68, 0x2, 0x2)
	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:134 +0x9c
main.main()
	knative.dev/operator/cmd/operator/main.go:25 +0x72
```

When we switch to use 0.17 knative/pkg, this is the error message.

**Comment by Harwayne** [comment]
> @Harwayne
> Do you know how to resolve this issue?
> 
> ```
> 2020/08/11 21:37:49 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
> 2020/08/11 21:37:49 Registering 2 clients
> 2020/08/11 21:37:49 Registering 3 informer factories
> 2020/08/11 21:37:49 Registering 3 informers
> 2020/08/11 21:37:49 Registering 2 controllers
> {"level":"info","ts":"2020-08-11T21:37:49.301Z","caller":"logging/config.go:110","msg":"Successfully created the logger."}
> {"level":"info","ts":"2020-08-11T21:37:49.302Z","caller":"logging/config.go:111","msg":"Logging level set to info"}
> {"level":"info","ts":"2020-08-11T21:37:49.302Z","caller":"logging/config.go:78","msg":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory"}
> {"level":"info","ts":"2020-08-11T21:37:49.302Z","logger":"knative-operator","caller":"profiling/server.go:59","msg":"Profiling enabled: false"}
> {"level":"info","ts":"2020-08-11T21:37:49.308Z","logger":"knative-operator","caller":"leaderelection/context.go:46","msg":"Running with Standard leader election"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ecc8b]
> 
> goroutine 1 [running]:
> k8s.io/client-go/rest.CopyConfig(0x0, 0xc00061b200)
> 	k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/rest/config.go:569 +0x3b
> k8s.io/client-go/dynamic.ConfigFor(0x0, 0xc00079f510)
> 	k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/dynamic/simple.go:41 +0x2f
> k8s.io/client-go/dynamic.NewForConfig(0x0, 0x4959f8, 0xc00061b4d0, 0x18d4ca0, 0x2d5c710)
> 	k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/dynamic/simple.go:63 +0x2f
> github.com/manifestival/client-go-client/pkg/dynamic.NewForConfig(0x0, 0x4959f8, 0xc0001b9d10, 0x18d4ca0, 0x2d5c710)
> 	github.com/manifestival/client-go-client@v0.2.3-0.20200702141517-e255fbf14f6f/pkg/dynamic/rest_mapper_resource_interface.go:18 +0x2f
> github.com/manifestival/client-go-client.NewClient(0x0, 0x18d4ca0, 0x2d5c710, 0x0, 0x0)
> 	github.com/manifestival/client-go-client@v0.2.3-0.20200702141517-e255fbf14f6f/client.go:24 +0x2f
> knative.dev/operator/pkg/reconciler/knativeserving.NewExtendedController.func1(0x1f42d00, 0xc00075bf80, 0x1f0bf80, 0xc000093320, 0x2d5c710)
> 	knative.dev/operator/pkg/reconciler/knativeserving/controller.go:52 +0x19b
> knative.dev/operator/pkg/reconciler/knativeserving.NewController(0x1f42d00, 0xc00075bf80, 0x1f0bf80, 0xc000093320, 0xc0002ebc00)
> 	knative.dev/operator/pkg/reconciler/knativeserving/controller.go:41 +0x5e
> knative.dev/pkg/injection/sharedmain.ControllersAndWebhooksFromCtors(0x1f42d00, 0xc00075bf80, 0xc000093320, 0xc00079ff68, 0x2, 0x2, 0x1, 0x37e11d600, 0x2540be400, 0x77359400, ...)
> 	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:396 +0x17b
> knative.dev/pkg/injection/sharedmain.MainWithConfig(0x1f43880, 0xc00000e118, 0x1b4a473, 0x10, 0xc000728000, 0xc00079ff68, 0x2, 0x2)
> 	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:216 +0x69c
> knative.dev/pkg/injection/sharedmain.MainWithContext(0x1f43880, 0xc00000e118, 0x1b4a473, 0x10, 0xc00079ff68, 0x2, 0x2)
> 	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:160 +0xd5
> knative.dev/pkg/injection/sharedmain.Main(0x1b4a473, 0x10, 0xc00079ff68, 0x2, 0x2)
> 	knative.dev/pkg@v0.0.0-20200811182305-91561f0a4117/injection/sharedmain/main.go:134 +0x9c
> main.main()
> 	knative.dev/operator/cmd/operator/main.go:25 +0x72
> ```
> 
> When we switch to use 0.17 knative/pkg, this is the error message.

I think this call to GetConfig is returning `nil` (pkg/reconciler/knativeserving/controller.go:52):

```golang
mfclient, err := mfc.NewClient(injection.GetConfig(ctx))
```

Investigating further to figure out why.

**Comment by Harwayne** [comment]
> > When we switch to use 0.17 knative/pkg, this is the error message.
> 
> I think this call to GetConfig is returning `nil` (pkg/reconciler/knativeserving/controller.go:52):
> 
> ```go
> mfclient, err := mfc.NewClient(injection.GetConfig(ctx))
> ```
> 
> Investigating further to figure out why.

Found the cause. Fix is in knative/pkg#1610. Once that is merged, we'll cherry-pick into release-0.17 and update this PR.

**Pull request merged**
