### PR TITLE
move to security guard 0.5

### PR DESCRIPTION
**Pull request by davidhadas**
Move to Guard 0.5

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve


/hold
@nak3  or @ReToCode  any objections?

**Comment by davidhadas** [comment]
> @davidhadas This PR looks fine in general, but watch this line: https://github.com/knative/operator/blob/main/pkg/reconciler/knativeserving/security/securityguard.go#L36
If you change the version, and need 1.9 to pick up this version, you have to change this map as well, https://github.com/knative/operator/blob/main/pkg/reconciler/knativeserving/security/securityguard.go#L36.
Otherwise, it still stays with 0.4.

@houshengbo 
This change is included in the changes made by this PR.

**Comment by nak3** [comment]
No objection for me :+1:

**Comment by ReToCode** [comment]
No objection for me 👍

**Pull request merged**
