### PR TITLE
[release-1.7] Update the fetcher to pick the correct kafka sources

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes: #1212

### CODE REVIEW

**Comment by houshengbo** [comment]
@pierDipi

**Review by pierDipi — COMMENTED** [review]
Are we running KafkaSource tests in CI?

Why is the PR targeting 1.7 instead of main first?

**Comment by houshengbo** [comment]
@pierDipi Will update the main for sure.

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
