### PR TITLE
Remove pingsource-mt-adapter from the list of unsupported HA

### PR DESCRIPTION
**Pull request by houshengbo**

### CODE REVIEW

**Comment by matzew** [comment]
@houshengbo why?
Please see herE: https://github.com/knative/operator/pull/740/files

**Comment by lionelvillard** [comment]
Because PingSource supports HA

**Comment by matzew** [comment]
See here: https://github.com/knative/operator/pull/740

**Comment by matzew** [comment]
and here: https://github.com/knative/operator/pull/740#issuecomment-909253885

**Comment by matzew** [comment]
@maschmid looks like with 0.26+ the PingSource MT adapter might again bug us ....

**Pull request merged**
