### PR TITLE
Feat: Istio gateway TLS support added

### LINKED ISSUE #1428: Unable to set tls on Istio Gateway
**Problem**
When trying to setup tls configuration in the Istio Gateway spec i get an error.

```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: igw-alb-internal
        servers:
          - hosts:
            - '*'
            port:
              name: https
              number: 443
              protocol: HTTPS
            tls:
              credentialName: star-igw-alb-tls
              mode: SIMPLE
      knative-local-gateway:
        selector:
          istio: igw-alb-internal
```

```
error: error validating "STDIN": error validating data: ValidationError(KnativeServing.spec.ingress.istio.knative-ingress-gateway.servers[0]): unknown field "tls" in dev.knative.operator.v1beta1.KnativeServing.spec.ingress.istio.knative-ingress-gateway.servers; if you choose to ignore these errors, turn validation off with --validate=false
```

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Knative events

**Exit Criteria**
I am able to setup tls spec in the Istio Gateway.

### PR DESCRIPTION
**Pull request by supu2**
Fixes #1428
## Proposed Changes

* The change allow manual TLS setup for Istio gateway.
* The changes tested on Knative operator 1.9.5 

## Example Configuration
```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: ingressgateway
        servers:
        - port:
            number: 80
            name: http
            protocol: HTTP
            target_port: 80
          hosts:
          - '*'
        - port:
            number: 443
            name: https
            protocol: HTTPS
            target_port: 8443
          tls:
            mode: SIMPLE
            credentialName: tls-certificate
          hosts:
          - '*'
  config:
    istio:
      local-gateway.knative-serving.knative-local-gateway: "knative-local-gateway.istio-system.svc.cluster.local"
```

### CODE REVIEW

**Comment by houshengbo** [comment]
@supu2 You only changed the schema to add the section of tls, but you did not implement in the code to pick up the fields and apply in the istio ingress.

**Comment by supu2** [comment]
@houshengbo  There is no need to develop code.  The variables pass the Istio gateway via https://github.com/knative/operator/blob/a25b890b036f7146fa28268f6f89888aa0596d0f/pkg/apis/operator/base/ingressconfiguration.go#L30

**Comment by supu2** [comment]
@houshengbo  Is there anything to help you about the MR?

**Comment by supu2** [comment]
> @supu2 You only changed the schema to add the section of tls, but you did not implement in the code to pick up the fields and apply in the istio ingress.

@houshengbo  following line of operator pass the TLS object to ISTIO CRD. I've implemented that changes on my cluster and its perfectly running from 6 month.
https://github.com/knative/operator/blob/a25b890b036f7146fa28268f6f89888aa0596d0f/pkg/apis/operator/base/ingressconfiguration.go#L30

**Comment by nguyenthai0107** [comment]
Hello @supu2 
im also need to implement gateway with tls, thank you so much with this MR.
Hope this MR will be merge soon.
Hello @houshengbo 
Could you take a look ?
Thank you guys.

**Comment by houshengbo** [comment]
@nguyenthai0107 I am wondering if u can join the knative org, so that we do not need to run `/ok-to-run` every time you changed the PR.

**Comment by houshengbo** [comment]
@supu2 The CR of the KnativeServing offers the options to configure the TLS, after you add the schema change in the CRD. When users configure this `tls` with the CR of KnativeServing, how could these values be passed to the istio gateway?
This is what I meant by `the implementation`.
If you think this implementation is already written with the source code, then would you mind adding some test cases covering them? Thank you.

**Comment by nguyenthai0107** [comment]
Hello guys.
@houshengbo @supu2 
Hope this available on next release with Helm Charts v0.40.2.
thank you so much.

**Pull request merged**
